version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/todo -schemas=public -user=postgres
      -password=password -connectRetries=5 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
  api:
    profiles: ["dev"]
    build:
      context: ./server
      dockerfile: dockerfile.local
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/todo?schema=public"
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    depends_on:
      - flyway
volumes:
  db: 